/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MessageType = IDL.Variant({
  'complaint' : IDL.Null,
  'inquiry' : IDL.Null,
  'suggestion' : IDL.Null,
  'praise' : IDL.Null,
});
export const InquiryInput = IDL.Record({
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'messageType' : MessageType,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'submitter' : IDL.Principal,
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'messageType' : MessageType,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createInquiry' : IDL.Func([InquiryInput], [IDL.Nat], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInquiry' : IDL.Func([IDL.Nat], [IDL.Opt(Inquiry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MessageType = IDL.Variant({
    'complaint' : IDL.Null,
    'inquiry' : IDL.Null,
    'suggestion' : IDL.Null,
    'praise' : IDL.Null,
  });
  const InquiryInput = IDL.Record({
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'messageType' : MessageType,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'submitter' : IDL.Principal,
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'messageType' : MessageType,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createInquiry' : IDL.Func([InquiryInput], [IDL.Nat], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInquiry' : IDL.Func([IDL.Nat], [IDL.Opt(Inquiry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };